using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using Ext;
using KModkit;
using UnityEngine;
using UnityEngine.UI;
using Rnd = UnityEngine.Random;

namespace Ext
{
	public static class Extensions
	{
		public static List<string> Chunk(this string str, int chunkSize)
		{
			if (str == "") return new List<string>();
			return Enumerable.Range(0, (str.Length - 1) / chunkSize + 1)
				.Select(i => str.Length>(i+1)*chunkSize?
					str.Substring(i * chunkSize, chunkSize):
					str.Substring(i * chunkSize))
				.ToList();
		}
		public static string toString<T>(this List<T> list){
			return "[" + list.Select(x=>x.ToString()).Aggregate((acc, x) => acc +", "+ x) + "]";
		}
	}
}

public class cosmoCipherScript : MonoBehaviour
{
	public List<KMSelectable> buttons;
	public TextMesh ansText, dwText, ktText;
	public AudioClip cookie, keyboard;

	private bool _moduleSelected, _moduleSolved;
	private string currentAnswer = "", generatedAnswer;
	private string ktEncrypt;
	private List<string> dwValues, ktPages;
	private int dwPage, ktPage;
	
	private static string alphabet = "ABCDEFGHIKLMNOPRSTUVWYZ";

	private static List<string> morse = new List<string>
	{
		".-", "-...", "-.-.", "-..", ".", "..-.", "--.", "....", "..", "-.-", ".-..", "--", 
		"-.", "---", ".--.", ".-.", "...", "-", "..-", "...-", ".--", "-.--", "--.."
	};
	private static List<string> possibleAnswers = new List<string>()
	{
		"ABACUS", "ABDUCT", "ABOARD", "ABOUND", "ABROAD", "ABRUPT", "ABSENT", "ABSORB", "ABSURD", "ABUSED", "ABUSER",
		"ABUSES", "ACACIA", "ACCEDE", "ACCENT", "ACCEPT", "ACCESS", "ACCORD", "ACCOST", "ACCRUE", "ACCUSE", "ACETIC",
		"ACHING", "ACIDIC", "ACROSS", "ACTING", "ACTION", "ACTIVE", "ACTORS", "ACTUAL", "ACUITY", "ACUMEN", "ADAGIO",
		"ADDICT", "ADDING", "ADHERE", "ADMIRE", "ADMITS", "ADORED", "ADRIFT", "ADULTS", "ADVENT", "ADVERB", "ADVERT",
		"ADVICE", "ADVISE", "AERIAL", "AFFAIR", "AFFECT", "AFFINE", "AFFIRM", "AFFORD", "AFGHAN", "AFIELD", "AFLAME",
		"AFLOAT", "AFRAID", "AFRESH", "AFRICA", "AGENCY", "AGENDA", "AGENTS", "AGHAST", "AGREED", "AGREES", "AIMING",
		"AIRBAG", "AIRING", "ALASKA", "ALBEIT", "ALBINO", "ALBUMS", "ALCOVE", "ALIENS", "ALKALI", "ALLEGE", "ALLELE",
		"ALLIED", "ALLIES", "ALLOWS", "ALLUDE", "ALLURE", "ALMOND", "ALMOST", "ALPACA", "ALPINE", "ALUMNA", "ALUMNI",
		"ALWAYS", "AMBUSH", "AMENDS", "AMIDST", "AMOEBA", "AMORAL", "AMOUNT", "AMULET", "AMUSED", "ANALOG", "ANCHOR",
		"ANEMIA", "ANEMIC", "ANGELS", "ANGINA", "ANGLED", "ANGLER", "ANGLES", "ANGORA", "ANIMAL", "ANKLES", "ANKLET",
		"ANNUAL", "ANOINT", "ANORAK", "ANSWER", "ANTHEM", "ANTICS", "ANTLER", "ANYHOW", "ANYONE", "ANYWAY", "AORTIC",
		"APACHE", "APATHY", "APIECE", "APOGEE", "APPALL", "APPEAL", "APPEAR", "APPEND", "APPLES", "APPLET", "ARCADE",
		"ARCANA", "ARCANE", "ARCHED", "ARCHER", "ARCHES", "ARCHLY", "ARCTIC", "ARDENT", "ARGUED", "ARGUES", "ARISEN",
		"ARISES", "ARMADA", "ARMFUL", "ARMIES", "ARMING", "ARMORY", "ARMOUR", "ARMPIT", "AROUND", "AROUSE", "ARREST",
		"ARRIVE", "ARROWS", "ARTERY", "ARTFUL", "ARTIST", "ASCEND", "ASCENT", "ASHORE", "ASKING", "ASLEEP", "ASPECT",
		"ASPIRE", "ASSENT", "ASSERT", "ASSESS", "ASSETS", "ASSIGN", "ASSIST", "ASSUME", "ASSURE", "ASTHMA", "ASTRAL",
		"ASTRAY", "ASTUTE", "ASYLUM", "ATOMIC", "ATONAL", "ATRIUM", "ATTACH", "ATTACK", "ATTAIN", "ATTEND", "ATTEST",
		"ATTIRE", "ATTUNE", "AUGUST", "AUNTIE", "AUTHOR", "AUTISM", "AUTUMN", "AVATAR", "AVENGE", "AVENUE", "AVERSE",
		"AVIARY", "AVIDLY", "AVOIDS", "AVOWAL", "AVOWED", "AWAKEN", "AWARDS", "AWHILE", "AWNING", "BABBLE", "BABIES",
		"BABOON", "BACKED", "BACKER", "BACKUP", "BADDIE", "BADGER", "BAFFLE", "BAGGED", "BAGGER", "BAGGIE", "BAITED",
		"BAKERY", "BAKING", "BALDLY", "BALLAD", "BALLET", "BALLOT", "BALSAM", "BAMBOO", "BANANA", "BANDED", "BANDIT",
		"BANGED", "BANGER", "BANISH", "BANKED", "BANKER", "BANNED", "BANNER", "BANTER", "BAOBAB", "BARBED", "BARBER",
		"BARELY", "BARIUM", "BARKER", "BARLEY", "BARMAN", "BARNET", "BARONS", "BARRED", "BARREL", "BARREN", "BARTER",
		"BASALT", "BASICS", "BASINS", "BASKET", "BASSET", "BATHER", "BATTEN", "BATTER", "BATTLE", "BAUBLE", "BEACON",
		"BEADED", "BEAGLE", "BEAKER", "BEAMED", "BEARER", "BEASTS", "BEATEN", "BEATER", "BEAUTY", "BEAVER", "BECAME",
		"BECKON", "BECOME", "BEDBUG", "BEDLAM", "BEDPAN", "BEEPER", "BEETLE", "BEFALL", "BEFORE", "BEGGAR", "BEGGED",
		"BEGINS", "BEHALF", "BEHAVE", "BEHEAD", "BEHEST", "BEHIND", "BEHOLD", "BEINGS", "BELIEF", "BELLOW", "BELONG",
		"BELTED", "BEMOAN", "BENIGN", "BERATE", "BEREFT", "BERLIN", "BESIDE", "BESTOW", "BETRAY", "BETTER", "BETTOR",
		"BEWARE", "BEYOND", "BIASED", "BICEPS", "BICKER", "BIDDER", "BIGGER", "BIGWIG", "BIKING", "BIKINI", "BILLOW",
		"BINARY", "BINDER", "BIOGAS", "BIONIC", "BIOPIC", "BIOPSY", "BIOTIC", "BIRDER", "BIRDIE", "BIRTHS", "BISECT",
		"BISHOP", "BISTRO", "BITING", "BITTEN", "BITTER", "BLACKS", "BLADES", "BLAMED", "BLANCH", "BLASTS", "BLEACH",
		"BLEARY", "BLIGHT", "BLITHE", "BLOCKS", "BLOCKY", "BLONDE", "BLOODY", "BLOTCH", "BLOUSE", "BLOWER", "BLUISH",
		"BLURRY", "BOARDS", "BOASTS", "BOBBLE", "BOBCAT", "BODEGA", "BODICE", "BODIES", "BODILY", "BOGGLE", "BOILED",
		"BOILER", "BOLDLY", "BOLERO", "BOLTED", "BOMBED", "BOMBER", "BONBON", "BONDED", "BONNET", "BONOBO", "BONSAI",
		"BOOGIE", "BOOKED", "BOOKIE", "BOOMER", "BOOTED", "BORDER", "BOREAL", "BORING", "BORROW", "BOSSES", "BOSTON",
		"BOTANY", "BOTHER", "BOTTLE", "BOTTOM", "BOUGHT", "BOUNCE", "BOUNCY", "BOUNDS", "BOUNTY", "BOVINE", "BOWING",
		"BOWLER", "BOWTIE", "BOYISH", "BRAINS", "BRAINY", "BRAISE", "BRAKES", "BRANCH", "BRANDS", "BRANDY", "BRASSY",
		"BRAWNY", "BREACH", "BREAKS", "BREAST", "BREATH", "BREECH", "BREEDS", "BRICKS", "BRIDAL", "BRIDGE", "BRIDLE",
		"BRIGHT", "BRINGS", "BROACH", "BROGUE", "BROKEN", "BROKER", "BROOCH", "BROOKS", "BROWSE", "BRUISE", "BRUNCH",
		"BRUSHY", "BRUTAL", "BUBBLE", "BUBBLY", "BUCKET", "BUCKLE", "BUDGET", "BUFFED", "BUFFER", "BUFFET", "BUGGER",
		"BUILDS", "BULLET", "BUMBLE", "BUMMED", "BUMMER", "BUMPER", "BUNDLE", "BUNGEE", "BUNGLE", "BUNKER", "BURDEN",
		"BUREAU", "BURGER", "BURIAL", "BURIED", "BURLAP", "BURNED", "BURNER", "BURROW", "BURSTS", "BUSBOY", "BUSHEL",
		"BUSHES", "BUSILY", "BUSING", "BUSMAN", "BUSTED", "BUSTLE", "BUTANE", "BUTLER", "BUTTER", "BUTTON", "BUYERS",
		"BUYING", "BUYOUT", "BYGONE", "BYPASS", "CABLES", "CACKLE", "CACTUS", "CAESAR", "CAIMAN", "CALICO", "CALLED",
		"CALLER", "CALLUS", "CALMLY", "CALVES", "CAMERA", "CAMPER", "CAMPUS", "CANADA", "CANALS", "CANARY", "CANCEL",
		"CANCER", "CANDID", "CANDLE", "CANDOR", "CANINE", "CANNED", "CANNON", "CANOLA", "CANOPY", "CANTER", "CANVAS",
		"CANYON", "CAPPED", "CAPTOR", "CARBON", "CAREEN", "CAREER", "CARERS", "CARESS", "CARING", "CARNAL", "CARPAL",
		"CARPET", "CARROT", "CARTEL", "CARTON", "CARVED", "CASEIN", "CASHEW", "CASING", "CASINO", "CASKET", "CASTER",
		"CASTLE", "CASUAL", "CATCHY", "CATION", "CATNAP", "CATNIP", "CATTLE", "CAUGHT", "CAUSAL", "CAUSED", "CAUSES",
		"CAVEAT", "CAVERN", "CAVIAR", "CAVING", "CAVITY", "CEASED", "CELERY", "CELLAR", "CELTIC", "CEMENT", "CENSOR",
		"CENSUS", "CENTER", "CENTRE", "CEREAL", "CESIUM", "CHAINS", "CHAIRS", "CHAISE", "CHAKRA", "CHALET", "CHALKY",
		"CHANCE", "CHANGE", "CHAPEL", "CHARGE", "CHARTS", "CHASER", "CHASTE", "CHATTY", "CHECKS", "CHEEKS", "CHEEKY",
		"CHEERS", "CHEERY", "CHEESE", "CHEESY", "CHERRY", "CHERUB", "CHEWED", "CHICKS", "CHIEFS", "CHILLY", "CHISEL",
		"CHIVES", "CHOICE", "CHOKED", "CHOKER", "CHOOSE", "CHOPPY", "CHORAL", "CHORDS", "CHORUS", "CHOSEN", "CHROME",
		"CHUBBY", "CHUNKS", "CHUNKY", "CHURCH", "CICADA", "CINDER", "CINEMA", "CIPHER", "CIRCLE", "CIRCUS", "CITIES",
		"CITING", "CITRUS", "CIVICS", "CLAIMS", "CLAMMY", "CLAMOR", "CLASSY", "CLAUSE", "CLAWED", "CLEAVE", "CLENCH",
		"CLERGY", "CLERIC", "CLERKS", "CLEVER", "CLICHE", "CLIENT", "CLIFFS", "CLINCH", "CLINGY", "CLINIC", "CLOCKS",
		"CLONED", "CLONES", "CLOSED", "CLOSER", "CLOSES", "CLOSET", "CLOTHE", "CLOUDS", "CLOUDY", "CLOVER", "CLUMPY",
		"CLUMSY", "CLUNKY", "CLUTCH", "COARSE", "COASTS", "COATED", "COBALT", "COBBLE", "COBWEB", "COCOON", "CODDLE",
		"CODIFY", "CODING", "COERCE", "COFFEE", "COFFER", "COFFIN", "COGNAC", "COHERE", "COHORT", "COILED", "COLDER",
		"COLDLY", "COLLAR", "COLONY", "COLORS", "COLUMN", "COMBAT", "COMEDY", "COMING", "COMMIT", "COMMON", "COMPEL",
		"COMPLY", "CONCUR", "CONDOR", "CONFER", "CONSUL", "CONVEY", "CONVOY", "COOKED", "COOKER", "COOKIE", "COOLED",
		"COOLER", "COPIED", "COPIER", "COPIES", "COPING", "COPPER", "CORDED", "CORDON", "CORNEA", "CORNED", "CORNER",
		"CORNET", "CORONA", "CORPSE", "CORPUS", "CORRAL", "CORSET", "COSMIC", "COSMOS", "COSTLY", "COTTON", "COUNTS",
		"COUNTY", "COUPLE", "COUPON", "COURSE", "COURTS", "COUSIN", "COVENT", "COVERS", "COVERT", "COWARD", "COWBOY",
		"COYOTE", "CRABBY", "CRACKS", "CRADLE", "CRAFTY", "CRANKY", "CRANNY", "CRATER", "CRAYON", "CREAKY", "CREAMY",
		"CREASE", "CREATE", "CREDIT", "CREEPY", "CREOLE", "CRETIN", "CREWED", "CRIMES", "CRINGE", "CRISES", "CRISIS",
		"CRISPS", "CRISPY", "CRITIC", "CROCUS", "CROTCH", "CROUCH", "CROWDS", "CRUISE", "CRUMMY", "CRUNCH", "CRUSTY",
		"CRUTCH", "CRYING", "CUBISM", "CUBIST", "CUCKOO", "CUDDLE", "CUDDLY", "CUPPED", "CURATE", "CURDLE", "CURFEW",
		"CURLED", "CURLER", "CURSED", "CURSOR", "CURTLY", "CURTSY", "CURVED", "CURVES", "CUSTOM", "CUTESY", "CUTLET",
		"CUTTER", "CYBORG", "CYCLES", "CYCLIC", "CYMBAL", "CYSTIC", "DABBLE", "DAGGER", "DAIKON", "DAINTY", "DAMAGE",
		"DAMPEN", "DAMPER", "DAMSEL", "DANCED", "DANCER", "DANCES", "DANDER", "DANGER", "DANGLE", "DANISH", "DAPPER",
		"DAPPLE", "DARING", "DARKEN", "DARKER", "DARKLY", "DARNED", "DASHED", "DASHER", "DATING", "DAWDLE", "DEADEN",
		"DEADLY", "DEAFEN", "DEALER", "DEARLY", "DEATHS", "DEBASE", "DEBATE", "DEBRIS", "DEBTOR", "DEBUNK", "DECADE",
		"DECAMP", "DECANT", "DECEIT", "DECENT", "DECIDE", "DECODE", "DECREE", "DEDUCE", "DEDUCT", "DEEMED", "DEEPEN",
		"DEEPER", "DEEPLY", "DEFACE", "DEFAME", "DEFANG", "DEFEAT", "DEFECT", "DEFEND", "DEFILE", "DEFINE", "DEFORM",
		"DEFRAY", "DEFTLY", "DEFUSE", "DEGREE", "DELAYS", "DELETE", "DELUDE", "DELUGE", "DEMAND", "DEMEAN", "DEMISE",
		"DEMONS", "DEMOTE", "DEMURE", "DENIAL", "DENIED", "DENIER", "DENIES", "DENOTE", "DENTAL", "DENTED", "DENUDE",
		"DEPART", "DEPEND", "DEPICT", "DEPLOY", "DEPORT", "DEPOSE", "DEPTHS", "DEPUTY", "DERAIL", "DERIDE", "DERIVE",
		"DERMAL", "DESERT", "DESIGN", "DESIRE", "DESIST", "DESPOT", "DETACH", "DETAIL", "DETAIN", "DETECT", "DETEST",
		"DETOUR", "DEVICE", "DEVILS", "DEVISE", "DEVOID", "DEVOTE", "DEVOUR", "DEVOUT", "DIADEM", "DIALOG", "DIAPER",
		"DIATOM", "DICTUM", "DIESEL", "DIFFER", "DIGEST", "DIGGER", "DIGITS", "DILATE", "DILUTE", "DIMMED", "DIMMER",
		"DIMPLE", "DINGHY", "DINING", "DINNER", "DIPOLE", "DIRECT", "DISARM", "DISBAR", "DISCUS", "DISHES", "DISMAL",
		"DISMAY", "DISOWN", "DISPEL", "DISUSE", "DITHER", "DIVERS", "DIVERT", "DIVEST", "DIVIDE", "DIVINE", "DIVING",
		"DOABLE", "DOCILE", "DOCKET", "DOCTOR", "DOGGIE", "DOINGS", "DOLLAR", "DOLLOP", "DOMAIN", "DOMINO", "DONATE",
		"DONKEY", "DONORS", "DOODAD", "DOODLE", "DOOMED", "DORSAL", "DOSAGE", "DOTING", "DOTTED", "DOUBLE", "DOUBLY",
		"DOUBTS", "DOUGHY", "DOVISH", "DOWNED", "DOWNER", "DRAFTY", "DRAGON", "DRAINS", "DRAPED", "DRAWER", "DREAMS",
		"DREAMY", "DREARY", "DREDGE", "DRENCH", "DRESSY", "DRINKS", "DRIPPY", "DRIVEL", "DRIVEN", "DRIVER", "DRIVES",
		"DROOPY", "DROWSE", "DROWSY", "DRUDGE", "DRYING", "DUFFEL", "DUGOUT", "DULLED", "DUMBLY", "DUMPED", "DURESS",
		"DURIAN", "DURING", "DUSTER", "DUTIES", "DYEING", "DYNAMO", "EAGLES", "EARFUL", "EARNED", "EARNER", "EARTHY",
		"EASIER", "EASILY", "EASING", "EASTER", "EATERY", "EATING", "ECHOED", "ECHOES", "ECLAIR", "EDGING", "EDIBLE",
		"EDITED", "EDITOR", "EERILY", "EFFECT", "EFFIGY", "EFFORT", "EGGNOG", "EGOISM", "EGRESS", "EIGHTH", "EIGHTY",
		"EITHER", "ELAPSE", "ELATED", "ELBOWS", "ELDERS", "ELDEST", "ELEVEN", "ELICIT", "ELITES", "ELVISH", "EMBALM",
		"EMBARK", "EMBLEM", "EMBODY", "EMBOSS", "EMBRYO", "EMERGE", "EMPIRE", "EMPLOY", "ENABLE", "ENAMEL", "ENCASE",
		"ENCODE", "ENCORE", "ENDEAR", "ENDING", "ENDURE", "ENERGY", "ENFOLD", "ENGAGE", "ENGINE", "ENGULF", "ENIGMA",
		"ENLIST", "ENMITY", "ENOUGH", "ENRAGE", "ENRICH", "ENROLL", "ENSURE", "ENTAIL", "ENTERS", "ENTICE", "ENTIRE",
		"ENTITY", "ENTOMB", "ENTRAP", "ENTREE", "ERASED", "ERASER", "ERODED", "ERRAND", "ERRANT", "ERRORS", "ESCAPE",
		"ESCHEW", "ESCORT", "ESSAYS", "ESTATE", "ESTEEM", "ETHICS", "ETHNIC", "EULOGY", "EUREKA", "EUROPE", "EVENLY",
		"EVENTS", "EVOLVE", "EYEFUL", "EYELID", "FABLED", "FABRIC", "FACADE", "FACETS", "FACIAL", "FACILE", "FACING",
		"FACTOR", "FADING", "FAILED", "FAIRLY", "FAKERY", "FAKING", "FALCON", "FALLEN", "FALTER", "FAMILY", "FAMINE",
		"FAMOUS", "FANDOM", "FARMED", "FARMER", "FASTEN", "FASTER", "FATHER", "FATHOM", "FATTEN", "FAUCET", "FAULTS",
		"FAULTY", "FAVOUR", "FEARED", "FEDORA", "FEEBLE", "FEEBLY", "FEEDER", "FEELER", "FEISTY", "FELINE", "FELLED",
		"FELLOW", "FELONY", "FEMALE", "FENCED", "FENCER", "FENCES", "FENDER", "FENNEL", "FERRET", "FESTER", "FETISH",
		"FETTER", "FEUDAL", "FIANCE", "FIASCO", "FIBRES", "FIBULA", "FICKLE", "FIDDLE", "FIDGET", "FIELDS", "FIERCE",
		"FIFTHS", "FIGHTS", "FIGURE", "FILIAL", "FILING", "FILLED", "FILLER", "FILLET", "FILMED", "FILTER", "FILTHY",
		"FINALE", "FINALS", "FINDER", "FINELY", "FINERY", "FINEST", "FINGER", "FINISH", "FINITE", "FIRING", "FIRMLY",
		"FISCAL", "FISHER", "FISTED", "FITTED", "FITTER", "FLABBY", "FLAMES", "FLANKS", "FLARED", "FLASHY", "FLATLY",
		"FLAUNT", "FLAVOR", "FLAWED", "FLEECE", "FLESHY", "FLIGHT", "FLIMSY", "FLINCH", "FLIRTY", "FLOCKS", "FLOODS",
		"FLOORS", "FLOPPY", "FLORAL", "FLOWED", "FLOWER", "FLUENT", "FLUFFY", "FLUIDS", "FLURRY", "FLUTED", "FLYING",
		"FLYWAY", "FODDER", "FOETUS", "FOILED", "FOLDED", "FOLDER", "FOLLOW", "FONDLE", "FONDLY", "FONDUE", "FOODIE",
		"FOOTER", "FORAGE", "FORBID", "FORCED", "FORCES", "FOREGO", "FOREST", "FORGED", "FORGER", "FORGET", "FORGOT",
		"FORKED", "FORMAL", "FORMAT", "FORMED", "FORMER", "FOSSIL", "FOSTER", "FOUGHT", "FOULED", "FOURTH", "FOWLER",
		"FRAMED", "FRAMER", "FRAMES", "FRANCE", "FRANCO", "FRANCS", "FRAYED", "FREAKY", "FREELY", "FRENCH", "FRESCO",
		"FRIDAY", "FRIDGE", "FRIEND", "FRIGHT", "FRIGID", "FRILLY", "FRINGE", "FRISKY", "FROLIC", "FRONTS", "FROSTY",
		"FROTHY", "FRUGAL", "FRUITS", "FRUITY", "FRYING", "FUELED", "FULFIL", "FULHAM", "FULLER", "FUMBLE", "FUNDED",
		"FUNDER", "FUNGAL", "FUNGUS", "FUNNEL", "FURROW", "FUSION", "FUTILE", "FUTURE", "GADFLY", "GADGET", "GAELIC",
		"GAFFER", "GAGGLE", "GAIETY", "GAINED", "GAINER", "GALLEY", "GALLON", "GALLOP", "GALORE", "GAMBIT", "GAMBLE",
		"GAMELY", "GAMETE", "GAMING", "GANDER", "GANGLY", "GANTRY", "GAPING", "GARAGE", "GARBLE", "GARDEN", "GARGLE",
		"GARISH", "GARLIC", "GARNER", "GARNET", "GASKET", "GASPED", "GATHER", "GEARED", "GEISHA", "GELATO", "GENDER",
		"GENEVA", "GENIAL", "GENIUS", "GENOME", "GENTLE", "GENTLY", "GENTRY", "GERBIL", "GERMAN", "GETTER", "GEYSER",
		"GHETTO", "GHOSTS", "GIANTS", "GIBLET", "GIFTED", "GIGGLE", "GILDED", "GINGER", "GIRDER", "GIRDLE", "GIRLIE",
		"GIVING", "GLADLY", "GLANCE", "GLANDS", "GLARED", "GLASSY", "GLIDER", "GLITCH", "GLOBAL", "GLOOMY", "GLOSSY",
		"GLOVED", "GLOVES", "GLOWER", "GLUMLY", "GLUTEN", "GLYCOL", "GNARLY", "GOALIE", "GOATEE", "GOBBLE", "GOBLET",
		"GOBLIN", "GOGGLE", "GOLDEN", "GOLFER", "GOODLY", "GOPHER", "GOSPEL", "GOSSIP", "GOTHIC", "GOTTEN", "GOVERN",
		"GRADED", "GRADER", "GRADES", "GRAHAM", "GRAINS", "GRAINY", "GRANNY", "GRANTS", "GRAPES", "GRAPHS", "GRASSY",
		"GRATED", "GRATER", "GRAVEL", "GRAVEN", "GRAVES", "GREASE", "GREASY", "GREECE", "GREEDY", "GREENS", "GRIEVE",
		"GRILLE", "GRIMLY", "GRINCH", "GRISLY", "GRITTY", "GROCER", "GROGGY", "GROOVE", "GROOVY", "GROTTO", "GROUCH",
		"GROUND", "GROUPS", "GROVEL", "GROWER", "GROWTH", "GRUBBY", "GRUDGE", "GRUMPY", "GRUNGE", "GRUNGY", "GUARDS",
		"GUESTS", "GUIDED", "GUIDES", "GUILTY", "GUINEA", "GUITAR", "GULLET", "GUNMAN", "GUNMEN", "GUNNER", "GURGLE",
		"GURNEY", "GUSHER", "GUTTED", "GUTTER", "GYPSUM", "GYRATE", "HABITS", "HACKER", "HADRON", "HAGGIS", "HAGGLE",
		"HAIRDO", "HALTED", "HALTER", "HALVED", "HALVES", "HAMLET", "HAMMER", "HAMPER", "HANDED", "HANDLE", "HANGAR",
		"HANGER", "HANKER", "HAPPEN", "HARASS", "HARBOR", "HARDEN", "HARDER", "HARDLY", "HARROW", "HASSLE", "HASTEN",
		"HATRED", "HAULED", "HAULER", "HAVING", "HEADED", "HEADER", "HEALED", "HEALER", "HEALTH", "HEARER", "HEARSE",
		"HEARTH", "HEARTS", "HEARTY", "HEATED", "HEATER", "HEAVED", "HEAVEN", "HECKLE", "HECTIC", "HEDGES", "HEIGHT",
		"HELIUM", "HELMET", "HELPED", "HELPER", "HERALD", "HERBAL", "HERDER", "HEREBY", "HEREIN", "HERESY", "HERMIT",
		"HERNIA", "HEROES", "HEROIC", "HEYDAY", "HIATUS", "HICCUP", "HIDDEN", "HIDING", "HIGHER", "HIGHLY", "HIKING",
		"HINDER", "HINGED", "HINGES", "HIPPIE", "HIRING", "HISSED", "HITHER", "HITMAN", "HITTER", "HOARSE", "HOBBIT",
		"HOBBLE", "HOBNOB", "HOCKEY", "HOLDER", "HOLDUP", "HOLLER", "HOLLOW", "HOMAGE", "HOMELY", "HOMING", "HONCHO",
		"HONEST", "HONOUR", "HOODED", "HOODIE", "HOOKED", "HOOKUP", "HOOPER", "HOOPLA", "HOORAY", "HOOVES", "HOPING",
		"HOPPER", "HORNED", "HORRID", "HORROR", "HORSES", "HORSEY", "HOSTEL", "HOTBED", "HOTDOG", "HOTELS", "HOTTIE",
		"HOUNDS", "HOURLY", "HOUSED", "HOUSES", "HOWLER", "HUBBUB", "HUBRIS", "HUDDLE", "HUGELY", "HUGGED", "HUGGER",
		"HUMANE", "HUMANS", "HUMBLE", "HUMBLY", "HUMBUG", "HUMMER", "HUMMUS", "HUMOUR", "HUMPED", "HUNGER", "HUNGRY",
		"HUNKER", "HUNTED", "HUNTER", "HURDLE", "HURRAH", "HUSHED", "HUSTLE", "HYBRID", "HYMNAL", "HYPHEN", "IAMBIC",
		"ICECAP", "ICICLE", "ICONIC", "IDEALS", "IDIOCY", "IDLING", "IGNITE", "IGNORE", "IGUANA", "IMAGES", "IMBIBE",
		"IMMUNE", "IMPACT", "IMPAIR", "IMPALE", "IMPART", "IMPEDE", "IMPISH", "IMPORT", "IMPOSE", "IMPROV", "IMPURE",
		"INCHES", "INCITE", "INCOME", "INDEED", "INDENT", "INDIAN", "INDICT", "INDIES", "INDIGO", "INDIUM", "INDOOR",
		"INDUCE", "INDUCT", "INFAMY", "INFANT", "INFECT", "INFEST", "INFILL", "INFIRM", "INFLOW", "INFORM", "INFUSE",
		"INGEST", "INHALE", "INKPOT", "INLAND", "INMATE", "INNATE", "INNING", "INPUTS", "INSANE", "INSECT", "INSERT",
		"INSIDE", "INSIST", "INSTEP", "INSTIL", "INSULT", "INSURE", "INTACT", "INTAKE", "INTEND", "INTENT", "INTERN",
		"INTUIT", "INVADE", "INVENT", "INVERT", "INVEST", "INVITE", "INVOKE", "INWARD", "IODIDE", "IODINE", "IRONED",
		"IRONIC", "ISLAND", "ISRAEL", "ISSUED", "ISSUER", "ISSUES", "ITSELF", "KABOOM", "KARATE", "KARMIC", "KEELED",
		"KEENLY", "KEEPER", "KELVIN", "KENNEL", "KERNEL", "KETTLE", "KEYPAD", "KHAKIS", "KIBBLE", "KICKED", "KICKER",
		"KIDDIE", "KIDNAP", "KIDNEY", "KILLED", "KILLER", "KIMONO", "KINDLE", "KINDLY", "KINGLY", "KIPPER", "KISSED",
		"KISSER", "KISSES", "KITSCH", "KITTEN", "KNIGHT", "KNIVES", "KNOCKS", "KNOTTY", "KNOWER", "KOREAN", "KOSHER",
		"KRAKEN", "LABELS", "LABOUR", "LACKED", "LACKEY", "LACTIC", "LADDER", "LADDIE", "LADIES", "LAGGED", "LAGOON",
		"LAMBDA", "LAMELY", "LAMENT", "LANCER", "LANDED", "LAPDOG", "LAPSED", "LAPTOP", "LARDER", "LARGER", "LARVAE",
		"LASERS", "LASHES", "LASTED", "LASTLY", "LATELY", "LATENT", "LATEST", "LATHER", "LATTER", "LAUDED", "LAUGHS",
		"LAUNCH", "LAVISH", "LAWFUL", "LAWMAN", "LAWYER", "LAYERS", "LAYING", "LAYMAN", "LAYOFF", "LAYOUT", "LEADED",
		"LEADER", "LEAGUE", "LEAKED", "LEAKER", "LEANED", "LEAPER", "LEARNS", "LEARNT", "LEASED", "LEASES", "LEAVEN",
		"LEAVER", "LEAVES", "LECTOR", "LEDGER", "LEEWAY", "LEGACY", "LEGATE", "LEGATO", "LEGEND", "LEGGED", "LEGION",
		"LEGUME", "LEMONY", "LENDER", "LENGTH", "LENSES", "LESION", "LESSEN", "LESSER", "LESSON", "LETHAL", "LETTER",
		"LEVELS", "LEVITY", "LIABLE", "LIBIDO", "LICHEN", "LICKED", "LIDDED", "LIFTED", "LIFTER", "LIGHTS", "LIKELY",
		"LIKING", "LIMBER", "LIMBIC", "LIMITS", "LIMPLY", "LINEAR", "LINEUP", "LINGER", "LINING", "LINKED", "LISTED",
		"LISTEN", "LITANY", "LITMUS", "LITRES", "LITTER", "LITTLE", "LIVELY", "LIVERY", "LIVING", "LOADED", "LOADER",
		"LOAFER", "LOANED", "LOANER", "LOATHE", "LOCALE", "LOCALS", "LOCATE", "LOCKED", "LOCKER", "LOCKET", "LOCKUP",
		"LOCUST", "LODGED", "LODGER", "LOGGER", "LOITER", "LONDON", "LONELY", "LONGED", "LONGER", "LOOKED", "LOOKER",
		"LOOKUP", "LOOPED", "LOOSEN", "LOOTED", "LOOTER", "LORDLY", "LOSERS", "LOSING", "LOSSES", "LOTION", "LOUDER",
		"LOUDLY", "LOUNGE", "LOVELY", "LOVERS", "LOVING", "LOWEST", "LUGGED", "LUMBAR", "LUMBER", "LUNACY", "LUPINE",
		"LUSTER", "LYCHEE", "LYRICS", "MADAME", "MADDEN", "MADMAN", "MAGGOT", "MAGNET", "MAGPIE", "MAIDEN", "MAILED",
		"MAILER", "MAIMED", "MAINLY", "MAKERS", "MAKEUP", "MAKING", "MALADY", "MALICE", "MALIGN", "MALLET", "MALTED",
		"MAMMAL", "MANAGE", "MANGER", "MANGLE", "MANIAC", "MANNED", "MANNER", "MANTIS", "MANTLE", "MANTRA", "MANUAL",
		"MANURE", "MARACA", "MARBLE", "MARCEL", "MARGIN", "MARINE", "MARKED", "MARKER", "MARKET", "MARKUP", "MARMOT",
		"MAROON", "MARROW", "MARSHY", "MARTIN", "MARTYR", "MARVEL", "MASCOT", "MASHED", "MASHER", "MASKED", "MASSES",
		"MASSIF", "MASTER", "MATING", "MATRON", "MATTED", "MATTER", "MATURE", "MAYDAY", "MAYFLY", "MAYHEM", "MEADOW",
		"MEAGER", "MEASLY", "MEDALS", "MEDDLE", "MEDIAN", "MEDIUM", "MEDLEY", "MEEKLY", "MELLOW", "MELODY", "MELTED",
		"MEMBER", "MEMOIR", "MEMORY", "MENACE", "MENIAL", "MENTAL", "MENTEE", "MENTOR", "MERELY", "MERGED", "MERGER",
		"MERITS", "MERLOT", "METALS", "METEOR", "METHOD", "METHYL", "METRES", "METRIC", "METTLE", "MIASMA", "MICRON",
		"MIDDAY", "MIDDLE", "MIDGET", "MIDWAY", "MIGHTY", "MIGNON", "MILADY", "MILDEW", "MILDLY", "MILLED", "MILLER",
		"MIMOSA", "MINCED", "MINDED", "MINERS", "MINGLE", "MINING", "MINION", "MINNOW", "MINUET", "MINUTE", "MIRAGE",
		"MIRROR", "MISERY", "MISFIT", "MISHAP", "MISLED", "MISSED", "MISSES", "MISSUS", "MISTER", "MISUSE", "MITTEN",
		"MOANED", "MOBILE", "MODELS", "MODERN", "MODEST", "MODIFY", "MODULE", "MODULO", "MOLDED", "MOLDER", "MOLTEN",
		"MOMENT", "MONDAY", "MONGOL", "MONIES", "MONKEY", "MONTHS", "MORALE", "MORALS", "MORBID", "MORGAN", "MORGUE",
		"MORMON", "MORSEL", "MORTAL", "MORTAR", "MOSAIC", "MOSTLY", "MOTHER", "MOTIFS", "MOTION", "MOTIVE", "MOTLEY",
		"MOTORS", "MOUSSE", "MOUTHS", "MOVIES", "MOVING", "MUDDLE", "MUFFIN", "MUFFLE", "MUGGER", "MULLET", "MUMBLE",
		"MURDER", "MURMUR", "MURPHY", "MUSCLE", "MUSEUM", "MUSING", "MUSKET", "MUSTER", "MUTANT", "MUTATE", "MUTELY",
		"MUTINY", "MUTTER", "MUTTON", "MUTUAL", "MYOPIC", "MYRIAD", "MYSELF", "MYSTIC", "MYTHIC", "MYTHOS", "NAMELY",
		"NAMING", "NAPALM", "NAPKIN", "NARROW", "NATION", "NATIVE", "NATURE", "NAUGHT", "NAUSEA", "NEARBY", "NEARER",
		"NEARLY", "NEATLY", "NEBULA", "NECTAR", "NEEDED", "NEEDLE", "NEGATE", "NELSON", "NEPHEW", "NERVES", "NESTED",
		"NESTER", "NESTLE", "NETHER", "NETTLE", "NEURAL", "NEURON", "NEUTER", "NEWBIE", "NEWEST", "NEWISH", "NEWTON",
		"NIBBLE", "NICELY", "NICEST", "NICKEL", "NIGHTS", "NIMBLE", "NIMBLY", "NIMBUS", "NINETY", "NIPPLE", "NITRIC",
		"NITWIT", "NOBLES", "NOBODY", "NODDED", "NODULE", "NOGGIN", "NOISES", "NOODLE", "NORDIC", "NORMAL", "NORMAN",
		"NOSIER", "NOSILY", "NOTARY", "NOTATE", "NOTICE", "NOTIFY", "NOTING", "NOTION", "NOUGHT", "NOVELS", "NOVICE",
		"NUANCE", "NUBILE", "NUCLEI", "NUDGER", "NUDGES", "NUDIST", "NUDITY", "NUGGET", "NUMBED", "NUMBER", "NUMBLY",
		"NURSED", "NURSES", "NUTMEG", "OBEYED", "OBLIGE", "OBLONG", "OBOIST", "OBSESS", "OBTAIN", "OBTUSE", "OCCULT",
		"OCCUPY", "OCCURS", "OCEANS", "OCELOT", "OCTANE", "OCTAVE", "OCULAR", "OCULUS", "ODDITY", "OFFEND", "OFFERS",
		"OFFICE", "OFFSET", "OILMAN", "OLDEST", "OLIVES", "OMELET", "ONIONS", "ONLINE", "ONWARD", "OPENED", "OPENER",
		"OPENLY", "OPERAS", "OPIATE", "OPIOID", "OPPOSE", "OPTICS", "OPTING", "OPTION", "ORACLE", "ORALLY", "ORANGE",
		"ORATOR", "ORCHID", "ORDAIN", "ORDEAL", "ORDERS", "ORGANS", "ORIENT", "ORIGIN", "ORNATE", "ORPHAN", "OSMIUM",
		"OTHERS", "OUNCES", "OUSTED", "OUSTER", "OUTAGE", "OUTBID", "OUTCRY", "OUTDID", "OUTFIT", "OUTING", "OUTLAW",
		"OUTLET", "OUTPUT", "OUTRUN", "OUTSET", "OUTWIT", "OVERDO", "OVERLY", "OWLISH", "OWNERS", "OWNING", "OYSTER",
		"PACIFY", "PACING", "PACKED", "PACKET", "PADDED", "PADDLE", "PAELLA", "PAGING", "PAGODA", "PAINED", "PAIRED",
		"PALACE", "PALATE", "PALLET", "PALLOR", "PALTRY", "PAMPER", "PANAMA", "PANDER", "PANELS", "PANTRY", "PAPACY",
		"PAPAYA", "PAPERS", "PAPERY", "PARADE", "PARCEL", "PARDON", "PARENT", "PARIAH", "PARING", "PARITY", "PARKED",
		"PARLAY", "PARLOR", "PARODY", "PAROLE", "PARROT", "PARSEC", "PARSON", "PARTED", "PARTLY", "PASSED", "PASSER",
		"PASSES", "PASTEL", "PASTOR", "PASTRY", "PATCHY", "PATENT", "PATHOS", "PATROL", "PATRON", "PATTED", "PATTEN",
		"PAUNCH", "PAUPER", "PAUSED", "PAVING", "PAYDAY", "PAYERS", "PAYING", "PAYOFF", "PAYOUT", "PEACHY", "PEAKED",
		"PEANUT", "PEARCE", "PEARLS", "PEARLY", "PEBBLE", "PECKER", "PECTIN", "PEDANT", "PEDDLE", "PEELED", "PEELER",
		"PEEPER", "PEERED", "PEEVED", "PELLET", "PELVIC", "PELVIS", "PENCIL", "PEOPLE", "PEPPER", "PEPTIC", "PERIOD",
		"PERISH", "PERMIT", "PERSON", "PERUSE", "PESTER", "PESTLE", "PETALS", "PETITE", "PETROL", "PEWTER", "PHARMA",
		"PHASED", "PHASES", "PHENOL", "PHLEGM", "PHOBIA", "PHOBIC", "PHONED", "PHONES", "PHONEY", "PHOTON", "PHOTOS",
		"PHRASE", "PICKED", "PICKER", "PICKET", "PICKLE", "PICKUP", "PICNIC", "PIDGIN", "PIECES", "PIERCE", "PIGEON",
		"PIGLET", "PIGPEN", "PIGSTY", "PILEUP", "PILFER", "PILLAR", "PILLOW", "PILOTS", "PIMPLE", "PINATA", "PINCER",
		"PINKIE", "PINNED", "PIPING", "PIRACY", "PIRATE", "PISSED", "PISTOL", "PITTED", "PLACED", "PLACER", "PLACES",
		"PLACID", "PLAGUE", "PLAINS", "PLANAR", "PLANES", "PLANET", "PLANTS", "PLASMA", "PLATES", "PLAYED", "PLAYER",
		"PLEASE", "PLEDGE", "PLENTY", "PLIANT", "PLIERS", "PLIGHT", "PLOUGH", "PLOWED", "PLUNGE", "PLURAL", "POCKET",
		"PODIUM", "POETIC", "POETRY", "POINTS", "POINTY", "POISED", "POISON", "POLICE", "POLICY", "POLISH", "POLITE",
		"POLLEN", "POMMEL", "PONCHO", "PONDER", "PONIES", "POODLE", "POOLED", "POORER", "POORLY", "POPLAR", "POPPED",
		"POPPER", "POROUS", "PORTAL", "PORTER", "POSING", "POSSUM", "POSTAL", "POSTED", "POSTER", "POTATO", "POTENT",
		"POTION", "POTTED", "POTTER", "POUNCE", "POUNDS", "POURED", "POWDER", "POWERS", "PRAISE", "PRANCE", "PRAYED",
		"PRAYER", "PREACH", "PREFAB", "PREFER", "PRESET", "PRESTO", "PRETTY", "PRICED", "PRICES", "PRICEY", "PRIEST",
		"PRIMAL", "PRIMED", "PRIMER", "PRIMLY", "PRINCE", "PRINTS", "PRIORY", "PRISON", "PRISSY", "PRIVET", "PROBES",
		"PROFIT", "PROMPT", "PROPEL", "PROPER", "PROTON", "PROVED", "PROVEN", "PROVES", "PRYING", "PSEUDO", "PSYCHE",
		"PSYCHO", "PUBLIC", "PUCKER", "PUDDLE", "PUEBLO", "PUFFED", "PUFFIN", "PULLED", "PULLER", "PULLEY", "PULPIT",
		"PULSAR", "PULSED", "PULSES", "PUMICE", "PUMMEL", "PUMPED", "PUMPER", "PUNDIT", "PUNISH", "PUPILS", "PUPPET",
		"PURELY", "PURIFY", "PURIST", "PURITY", "PURPLE", "PURSUE", "PUSHED", "PUSHER", "PUTRID", "PUTTER", "PYTHON",
		"RABBIT", "RABBLE", "RABIES", "RACIAL", "RACING", "RACKET", "RADIAL", "RADIAN", "RADIOS", "RADISH", "RADIUM",
		"RADIUS", "RAFFLE", "RAFTER", "RAGGED", "RAGING", "RAGTAG", "RAISED", "RAISES", "RAISIN", "RAKING", "RAMBLE",
		"RANCID", "RANCOR", "RANDOM", "RANGED", "RANGES", "RANKED", "RANSOM", "RAPIER", "RAPPEL", "RAPPER", "RAPTOR",
		"RARELY", "RARITY", "RASCAL", "RASHES", "RATHER", "RATIFY", "RATING", "RATION", "RATIOS", "RATTLE", "RAVINE",
		"RAVING", "RAVISH", "READER", "REALLY", "REAPER", "REASON", "REBELS", "REBOOT", "REBORN", "REBUFF", "REBUKE",
		"RECALL", "RECANT", "RECAST", "RECEDE", "RECENT", "RECESS", "RECIPE", "RECITE", "RECKON", "RECODE", "RECOIL",
		"RECORD", "RECTAL", "RECTUM", "RECUSE", "REDDEN", "REDEEM", "REDIAL", "REDRAW", "REDUCE", "REFERS", "REFILL",
		"REFINE", "REFORM", "REFUEL", "REFUGE", "REFUND", "REFUSE", "REFUTE", "REGAIN", "REGALE", "REGARD", "REGENT",
		"REGGAE", "REGIME", "REGION", "REGRET", "REGROW", "REHASH", "REHEAT", "RELATE", "RELENT", "RELICS", "RELIED",
		"RELIEF", "RELIES", "RELISH", "RELIVE", "RELOAD", "REMAIN", "REMAKE", "REMARK", "REMEDY", "REMIND", "REMISS",
		"REMOTE", "REMOVE", "RENAME", "RENDER", "RENEGE", "RENOWN", "RENTAL", "RENTED", "RENTER", "REOPEN", "REPAIR",
		"REPEAL", "REPEAT", "REPENT", "REPLAY", "REPORT", "REPOSE", "REPUTE", "REREAD", "RESCUE", "RESEAL", "RESENT",
		"RESIDE", "RESIGN", "RESIST", "RESORT", "RESTED", "RESULT", "RESUME", "RETAIL", "RETAIN", "RETAKE", "RETEST",
		"RETINA", "RETIRE", "RETORT", "RETURN", "REVAMP", "REVEAL", "REVERB", "REVERE", "REVERT", "REVIEW", "REVILE",
		"REVISE", "REVIVE", "REVOKE", "REVOLT", "REWARD", "REWIND", "REWIRE", "REWORK", "RHESUS", "RHUMBA", "RHYTHM",
		"RIBALD", "RIBBED", "RIBBON", "RICHER", "RICHES", "RICHLY", "RIDDEN", "RIDDLE", "RIDERS", "RIDGED", "RIDGES",
		"RIDING", "RIFLES", "RIGGED", "RIGGER", "RIGHTS", "RIMMED", "RINGED", "RINGER", "RINSED", "RIOTER", "RIPPED",
		"RIPPER", "RIPPLE", "RISING", "RITUAL", "RIVALS", "RIVERS", "ROADIE", "ROARED", "ROBBER", "ROBOTS", "ROBUST",
		"ROCKER", "ROCKET", "ROCOCO", "RODENT", "ROLLED", "ROLLER", "ROMANS", "ROOKIE", "ROOMIE", "ROOTED", "ROPING",
		"ROSARY", "ROSTER", "ROTARY", "ROTATE", "ROTTED", "ROTTEN", "ROTUND", "ROUNDS", "ROUTER", "ROUTES", "ROVERS",
		"ROVING", "ROWING", "RUBBED", "RUBBER", "RUBBLE", "RUBRIC", "RUCKUS", "RUDDER", "RUDELY", "RUDEST", "RUEFUL",
		"RUFFLE", "RUGGED", "RUINED", "RULERS", "RULING", "RUMBLE", "RUMOUR", "RUMPLE", "RUNNER", "RUNOFF", "RUNWAY",
		"RUSHED", "RUSHER", "RUSSIA", "RUSTED", "RUSTIC", "RUSTLE", "RUTTED", "SACKED", "SACRED", "SADDEN", "SADDLE",
		"SADISM", "SADIST", "SAFARI", "SAFELY", "SAFEST", "SAFETY", "SAGELY", "SAILED", "SAILOR", "SAINTS", "SALADS",
		"SALAMI", "SALARY", "SALINE", "SALIVA", "SALMON", "SALOON", "SALTED", "SALUTE", "SAMPLE", "SANDAL", "SANITY",
		"SAPPER", "SARONG", "SASHAY", "SATIRE", "SAUCER", "SAUTED", "SAVAGE", "SAVANT", "SAVING", "SAVIOR", "SAVORY",
		"SAWING", "SAYING", "SCALAR", "SCALED", "SCALES", "SCANTY", "SCARAB", "SCARCE", "SCARED", "SCENES", "SCENIC",
		"SCHEMA", "SCHEME", "SCHISM", "SCHOOL", "SCONCE", "SCORCH", "SCORED", "SCORER", "SCORES", "SCOTCH", "SCOUTS",
		"SCRAPE", "SCRAPS", "SCRAWL", "SCREAM", "SCREEN", "SCREWS", "SCREWY", "SCRIBE", "SCRIPT", "SCROLL", "SCRUFF",
		"SCULPT", "SCURRY", "SCURVY", "SCYTHE", "SEABED", "SEALED", "SEALER", "SEAMAN", "SEAMEN", "SEANCE", "SEARCH",
		"SEARED", "SEASON", "SEATED", "SECEDE", "SECOND", "SECRET", "SECTOR", "SECURE", "SEDATE", "SEDUCE", "SEEDED",
		"SEEING", "SEEKER", "SEEMED", "SEEMLY", "SEESAW", "SEETHE", "SELDOM", "SELECT", "SELLER", "SENATE", "SENDER",
		"SENILE", "SENIOR", "SENSED", "SENSES", "SENSOR", "SENTRY", "SEPSIS", "SEPTAL", "SEPTET", "SEPTIC", "SEPTUM",
		"SERAPH", "SERENE", "SERIAL", "SERIES", "SERMON", "SERVED", "SERVER", "SERVES", "SESAME", "SETTEE", "SETTLE",
		"SEVENS", "SEVERE", "SEWAGE", "SEWING", "SHABBY", "SHADED", "SHADES", "SHADOW", "SHAFTS", "SHAGGY", "SHAKEN",
		"SHAKER", "SHAMAN", "SHANTY", "SHAPED", "SHAPES", "SHARED", "SHARES", "SHAVED", "SHAVEN", "SHEARS", "SHEATH",
		"SHEETS", "SHEILA", "SHEKEL", "SHELLS", "SHELVE", "SHERRY", "SHIELD", "SHIFTS", "SHIFTY", "SHIMMY", "SHINER",
		"SHIRTS", "SHIVER", "SHOCKS", "SHODDY", "SHOGUN", "SHORES", "SHORTS", "SHOULD", "SHOUTS", "SHOVEL", "SHOWED",
		"SHOWER", "SHREWD", "SHRIEK", "SHRILL", "SHRIMP", "SHRINE", "SHRINK", "SHROUD", "SHRUBS", "SHTICK", "SHUCKS",
		"SICKEN", "SICKLE", "SICKLY", "SIDING", "SIENNA", "SIERRA", "SIESTA", "SIFTED", "SIFTER", "SIGHED", "SIGHTS",
		"SIGNAL", "SIGNED", "SIGNER", "SILENT", "SILKEN", "SILVER", "SIMIAN", "SIMILE", "SIMMER", "SIMPLE", "SIMPLY",
		"SINFUL", "SINGED", "SINGER", "SINGLE", "SINKER", "SINNER", "SIPHON", "SIPPED", "SISTER", "SITCOM", "SITTER",
		"SKATER", "SKETCH", "SKEWED", "SKEWER", "SKIING", "SKILLS", "SKIMPY", "SKINNY", "SKIRTS", "SLALOM", "SLATER",
		"SLAVES", "SLAYER", "SLEDGE", "SLEEPY", "SLEEVE", "SLEIGH", "SLEUTH", "SLICED", "SLICER", "SLICES", "SLIDER",
		"SLIDES", "SLIGHT", "SLINKY", "SLIVER", "SLOGAN", "SLOPED", "SLOPES", "SLOPPY", "SLOUCH", "SLOUGH", "SLOWED",
		"SLOWER", "SLOWLY", "SLUDGE", "SLURRY", "SLUSHY", "SMARMY", "SMARTS", "SMELLS", "SMELLY", "SMILED", "SMILES",
		"SMITHY", "SMOKED", "SMOKER", "SMOOCH", "SMOOTH", "SMUDGE", "SMUGLY", "SNAKES", "SNAPPY", "SNARKY", "SNATCH",
		"SNEAKY", "SNIPER", "SNIPPY", "SNITCH", "SNOBBY", "SNOOPY", "SNOOTY", "SNUGLY", "SOAKED", "SOAKER", "SOCCER",
		"SOCIAL", "SOCKET", "SODDEN", "SODIUM", "SODOMY", "SOFTEN", "SOFTER", "SOFTIE", "SOFTLY", "SOILED", "SOIREE",
		"SOLACE", "SOLDER", "SOLELY", "SOLEMN", "SOLIDS", "SOLVED", "SOLVER", "SOMBER", "SOMBRE", "SONATA", "SONNET",
		"SOONER", "SOOTHE", "SORBET", "SORDID", "SORELY", "SORROW", "SORTED", "SORTER", "SOUGHT", "SOUNDS", "SOURCE",
		"SOURED", "SOURLY", "SOVIET", "SOWING", "SPACER", "SPACES", "SPARED", "SPARSE", "SPEAKS", "SPEECH", "SPEEDO",
		"SPEEDS", "SPEEDY", "SPELLS", "SPENDS", "SPHERE", "SPICED", "SPIDER", "SPIGOT", "SPIKED", "SPINAL", "SPINES",
		"SPIRAL", "SPIRIT", "SPLASH", "SPLEEN", "SPLICE", "SPLINT", "SPOILS", "SPOKEN", "SPONGE", "SPONGY", "SPOOKY",
		"SPORTS", "SPORTY", "SPOTTY", "SPOUSE", "SPRAIN", "SPRANG", "SPRAWL", "SPREAD", "SPRING", "SPRINT", "SPRITE",
		"SPROUT", "SPRUCE", "SPUNKY", "SPYING", "STABLE", "STACKS", "STAGED", "STAGES", "STAIRS", "STAKES", "STALLS",
		"STAMEN", "STAMPS", "STANCE", "STANDS", "STAPLE", "STARCH", "STARED", "STARRY", "STARTS", "STARVE", "STASIS",
		"STATED", "STATES", "STATIC", "STATUE", "STATUS", "STAYED", "STEADY", "STEAMY", "STEELY", "STEERS", "STENCH",
		"STEREO", "STEWED", "STICKS", "STICKY", "STIFLE", "STIGMA", "STINGY", "STINKY", "STITCH", "STOCKS", "STOCKY",
		"STOLEN", "STOLID", "STONED", "STONES", "STOOGE", "STORED", "STORES", "STOREY", "STORMS", "STORMY", "STRAFE",
		"STRAIN", "STRAND", "STRAPS", "STRATA", "STREAK", "STREAM", "STREET", "STRESS", "STRICT", "STRIDE", "STRIFE",
		"STRIKE", "STRING", "STRIPE", "STRIPS", "STRIVE", "STROBE", "STRODE", "STROKE", "STROLL", "STRONG", "STRUCK",
		"STRUNG", "STUBBY", "STUCCO", "STUDIO", "STUFFY", "STUMPY", "STUPID", "STUPOR", "STURDY", "STYLES", "STYLUS",
		"STYMIE", "SUBDUE", "SUBMIT", "SUBSET", "SUBTLE", "SUBTLY", "SUBURB", "SUBWAY", "SUCCOR", "SUCKED", "SUCKER",
		"SUCKLE", "SUDDEN", "SUFFER", "SUGARY", "SUITED", "SUITOR", "SULFUR", "SULLEN", "SULTRY", "SUMMED", "SUMMER",
		"SUMMIT", "SUMMON", "SUNDAE", "SUNDAY", "SUNDER", "SUNDRY", "SUNKEN", "SUNLIT", "SUNSET", "SUNTAN", "SUPERB",
		"SUPINE", "SUPPER", "SUPPLE", "SUPPLY", "SURELY", "SURFER", "SURVEY", "SUTURE", "SWAMPY", "SWANKY", "SWATHE",
		"SWEATY", "SWEETS", "SWERVE", "SWITCH", "SWIVEL", "SWORDS", "SYMBOL", "SYRUPY", "SYSTEM", "TABLES", "TABLET",
		"TACKLE", "TACTIC", "TAGGED", "TAILOR", "TAKING", "TALBOT", "TALENT", "TALKED", "TALKER", "TALKIE", "TALLER",
		"TALLOW", "TAMALE", "TAMERS", "TAMING", "TAMPER", "TAMPON", "TANDEM", "TANGLE", "TANKER", "TANNED", "TAPING",
		"TAPPED", "TARGET", "TARIFF", "TARMAC", "TARRED", "TARTAN", "TARTAR", "TARTLY", "TASSEL", "TASTED", "TASTER",
		"TASTES", "TATTLE", "TATTOO", "TAUGHT", "TAVERN", "TAWDRY", "TEACUP", "TEAPOT", "TEASED", "TEASER", "TECHIE",
		"TECHNO", "TEDIUM", "TEENSY", "TEEPEE", "TEETER", "TELLER", "TEMPER", "TEMPLE", "TENANT", "TENDED", "TENDER",
		"TENDON", "TENNIS", "TENPIN", "TENSOR", "TENTHS", "TENURE", "TERMED", "TERROR", "TESTED", "TESTER", "TETHER",
		"TETRIS", "THANKS", "THATCH", "THAWED", "THEIRS", "THEISM", "THEMED", "THEMES", "THEORY", "THESES", "THESIS",
		"THIGHS", "THINGS", "THINGY", "THINKS", "THINLY", "THIRDS", "THIRST", "THIRTY", "THORNY", "THOUGH", "THRALL",
		"THRASH", "THREAD", "THREAT", "THRICE", "THRIFT", "THRILL", "THRIVE", "THROAT", "THROES", "THRONE", "THRONG",
		"THROWN", "THROWS", "THRUSH", "THRUST", "THUSLY", "THWACK", "THWART", "TICKER", "TICKET", "TICKLE", "TIDBIT",
		"TIDING", "TIERED", "TIGERS", "TIGHTS", "TILING", "TILTED", "TIMBER", "TIMBRE", "TIMELY", "TIMING", "TINDER",
		"TINGLE", "TINKER", "TINKLE", "TINNED", "TINSEL", "TINTED", "TIPPED", "TIPPET", "TIPTOE", "TIRADE", "TIRING",
		"TISSUE", "TITLED", "TITLES", "TITTER", "TOASTY", "TODDLE", "TOFFEE", "TOGGLE", "TOILET", "TOKENS", "TOMATO",
		"TOMBOY", "TOMCAT", "TONGUE", "TONNES", "TONSIL", "TOOLED", "TOOTHY", "TOPICS", "TOPPED", "TOPPER", "TOPPLE",
		"TORPID", "TORPOR", "TORRID", "TOSSED", "TOUCAN", "TOUCHY", "TOUPEE", "TOUSLE", "TOWARD", "TOWELS", "TOWERS",
		"TOWING", "TRACED", "TRACER", "TRACES", "TRACKS", "TRACTS", "TRADED", "TRADER", "TRADES", "TRAGIC", "TRAINS",
		"TRAITS", "TRANCE", "TRASHY", "TRAUMA", "TRAVEL", "TREATS", "TREATY", "TREBLE", "TREMOR", "TRENCH", "TRENDS",
		"TRENDY", "TRIAGE", "TRIALS", "TRIBAL", "TRIBES", "TRICKS", "TRICKY", "TRIFLE", "TRIPLE", "TRIPOD", "TRIPPY",
		"TRIVIA", "TROOPS", "TROPHY", "TROPIC", "TROUGH", "TROUPE", "TROWEL", "TRUANT", "TRUCKS", "TRUDGE", "TRUISM",
		"TRUSTS", "TRUSTY", "TRUTHS", "TRYING", "TRYOUT", "TUBING", "TUCKED", "TUCKER", "TUGGED", "TUMBLE", "TUMOUR",
		"TUMULT", "TUNDRA", "TUNING", "TUNNEL", "TURBAN", "TURBID", "TURGID", "TURKEY", "TURNED", "TURNIP", "TURRET",
		"TURTLE", "TUSSLE", "TUTORS", "TWELVE", "TWENTY", "TWINGE", "TWISTY", "TWITCH", "TYCOON", "TYPING", "TYPIST",
		"TYRANT", "ULCERS", "ULTIMA", "UMPIRE", "UNABLE", "UNBEND", "UNBIND", "UNBORN", "UNCLIP", "UNCLOG", "UNCOIL",
		"UNCORK", "UNCURL", "UNDEAD", "UNDONE", "UNEASE", "UNEASY", "UNEVEN", "UNFAIR", "UNFELT", "UNFOLD", "UNFURL",
		"UNHOLY", "UNHOOK", "UNHURT", "UNIONS", "UNISON", "UNITED", "UNKIND", "UNLESS", "UNLIKE", "UNLOAD", "UNLOCK",
		"UNMASK", "UNPACK", "UNPAID", "UNPLUG", "UNREAD", "UNREAL", "UNREST", "UNRIPE", "UNROLL", "UNRULY", "UNSAFE",
		"UNSAID", "UNSEAL", "UNSEEN", "UNSOLD", "UNSUNG", "UNSURE", "UNTIDY", "UNTIED", "UNTOLD", "UNTRUE", "UNUSED",
		"UNVEIL", "UNWELL", "UNWIND", "UNWISE", "UNWORN", "UNWRAP", "UPBEAT", "UPDATE", "UPHELD", "UPHILL", "UPHOLD",
		"UPKEEP", "UPLIFT", "UPLINK", "UPLOAD", "UPROAR", "UPROOT", "UPSHOT", "UPSIDE", "UPTAKE", "UPTICK", "UPTIME",
		"UPTOWN", "UPWARD", "URCHIN", "URGENT", "URGING", "URINAL", "USABLE", "USEFUL", "UTERUS", "UTMOST", "UTOPIA",
		"VACANT", "VACATE", "VACUUM", "VAINLY", "VALLEY", "VALUED", "VALUES", "VALVES", "VANDAL", "VANISH", "VANITY",
		"VAPOUR", "VARIED", "VARIES", "VASTLY", "VAULTS", "VECTOR", "VEGGIE", "VEILED", "VEINED", "VELVET", "VENDOR",
		"VENTED", "VENUES", "VERBAL", "VERIFY", "VERMIN", "VERSED", "VERSES", "VERSUS", "VESSEL", "VIABLE", "VICTIM",
		"VICTOR", "VIDEOS", "VIEWED", "VIEWER", "VIGOUR", "VIKING", "VILIFY", "VILLAS", "VIOLET", "VIOLIN", "VIRGIN",
		"VIRTUE", "VISAGE", "VISION", "VISITS", "VISUAL", "VOICED", "VOICES", "VOIDED", "VOLLEY", "VOLUME", "VOODOO",
		"VOTERS", "VOTING", "VOWELS", "VOYAGE", "VOYEUR", "VULGAR", "WADDLE", "WADING", "WAFFLE", "WAGONS", "WAITED",
		"WAITER", "WAIVER", "WAKING", "WALKED", "WALKER", "WALLED", "WALLET", "WALNUT", "WALRUS", "WANDER", "WANING",
		"WANTED", "WANTON", "WARDEN", "WARDER", "WARILY", "WARMED", "WARMER", "WARMLY", "WARMTH", "WARNED", "WARPED",
		"WASABI", "WASHED", "WASHER", "WASTED", "WASTES", "WATERS", "WATERY", "WAVING", "WEAKEN", "WEAKER", "WEAKLY",
		"WEALTH", "WEANED", "WEAPON", "WEARER", "WEASEL", "WEBBED", "WEBCAM", "WEDDED", "WEEKLY", "WEENIE", "WEEVIL",
		"WEIGHT", "WEIRDO", "WELDED", "WELDER", "WETTER", "WHALES", "WHEELS", "WHILST", "WHIMSY", "WHINER", "WHINNY",
		"WHISKY", "WHITEN", "WHITES", "WHOLLY", "WICKED", "WIDELY", "WIDEST", "WIDGET", "WIDOWS", "WIENER", "WIGGLE",
		"WILDLY", "WILLOW", "WILTED", "WINDED", "WINDOW", "WINERY", "WINGED", "WINNER", "WINTER", "WINTRY", "WIPING",
		"WIRING", "WISDOM", "WISELY", "WISHED", "WISHES", "WITHER", "WITHIN", "WOBBLE", "WOBBLY", "WOEFUL", "WOLVES",
		"WOMBAT", "WONDER", "WOODED", "WOODEN", "WOOING", "WOOLEN", "WOOLLY", "WORKED", "WORKER", "WORLDS", "WORSEN",
		"WORTHY", "WOUNDS", "WRAITH", "WREATH", "WRENCH", "WRETCH", "WRISTS", "WRITER", "WRITES", "WRITHE", "WYVERN",
		"YACHTS", "YEARLY", "YELLED", "YELLER", "YELLOW", "YIELDS", "YIPPEE", "YONDER", "YOUTHS", "YUPPIE"
	};

	private static List<int> inverseModulars = new List<int>
		{ 0, 1, 12, 8, 6, 14, 4, 10, 3, 18, 7, 21, 2, 16, 5, 20, 13, 19, 9, 17, 15, 11, 12 };

	bool areCoprime(int a, int b) =>
		new List<int> { 2, 3, 5, 7, 11, 13, 17, 19 }.Where(x => a % x == 0).All(x => b % x != 0);
	
	
	// Use this for initialization
	void Start () {
		GetComponent<KMSelectable>().OnFocus += delegate { _moduleSelected = true; };
		GetComponent<KMSelectable>().OnDefocus += delegate { _moduleSelected = false; };
		generate();
		buttons[0].OnInteract+= delegate
		{
			GetComponent<KMAudio>().HandlePlaySoundAtTransform(cookie.name, transform);
			if (_moduleSolved) return false;
			if (dwPage == 0) return false;
			dwPage--;
			updateScreens();
			return false;
		};
		buttons[1].OnInteract+= delegate
		{
			GetComponent<KMAudio>().HandlePlaySoundAtTransform(cookie.name, transform);
			if (_moduleSolved) return false;
			if (dwPage == 2) return false;
			dwPage++;
			updateScreens();
			return false;
		};
		buttons[2].OnInteract+= delegate
		{
			GetComponent<KMAudio>().HandlePlaySoundAtTransform(keyboard.name, transform);
			if (_moduleSolved) return false;
			if (ktPage == 0) return false;
			ktPage--;
			updateScreens();
			return false;
		};
		buttons[3].OnInteract+= delegate
		{
			GetComponent<KMAudio>().HandlePlaySoundAtTransform(keyboard.name, transform);
			if (_moduleSolved) return false;
			if (ktPage == ktPages.Count-1) return false;
			ktPage++;
			updateScreens();
			return false;
		};
		updateScreens();
	}

	void generate()
	{
		generatedAnswer = possibleAnswers.PickRandom();
		print(generatedAnswer);
		List<int> x = Enumerable.Range(0, 3).Select(_ => Rnd.Range(1, 23)).ToList();
		List<int> y = x.Select(i => Enumerable.Range(1, 22).Where(j => areCoprime(i, j)).PickRandom()).ToList();
		
		// (x,y) converts to k = ln2 / tan(y/x).
		// nvm i'm stoopid it's arctan :P
		print("x: " + x.toString() + "; y: " + y.toString());
		
		List<double> k = Enumerable.Range(0,3).Select(i=>
		{
			int sn = GetComponent<KMBombInfo>().GetSerialNumberNumbers().Last();
			int n = (int)((new List<int>{200,250,270,300,340}.PickRandom() * Math.Log(2 + sn) - Math.Atan((double)y[i] / x[i])) / (2 * Math.PI)) + 1;
			return (Math.Atan((double)y[i] / x[i]) + Math.PI * n * 2) / Math.Log(2 + sn);
		}).ToList();
		dwValues = k.Select(v => v.ToString("F6").Substring(0,7)).ToList();
		
		List<int> ktEnc = Enumerable.Range(0, 6).Select(i => i % 2 == 0 ? x[i / 2] : y[i / 2]).Select((v, i) =>
			(inverseModulars[v] * (alphabet.IndexOf(generatedAnswer[i]) + 1)-1) % 23).ToList();
		print(ktEnc.toString());
		List<string> ktMorse = ktEnc.Select(v => 
			morse[v].ToCharArray().Aggregate("", (a,b)=>
				a+" "+b)).ToList();
		string ktString = ktMorse.Aggregate("", (a, b) => a + "   " + b).Trim();
		char spaceConfig;
		print("" + ktString[0] + ktString[ktString.Length - 1]);
		switch ("" + ktString[0] + ktString[ktString.Length - 1])
		{
			case "..": spaceConfig = '.'; break;
			case ".-": spaceConfig = '!'; break;
			case "-.": spaceConfig = '?'; break;
			case "--": spaceConfig = '#'; break;
			default: spaceConfig = '$'; break;
		}
			ktString = ktString
			.Replace("-","/")
			.Replace(".","")
			.Replace("   ","-")
			.Replace(" ",".");
		print(ktString);
		ktEncrypt = ktString.Split('/').Where(s=>s!="").Select(s =>
		{
			if (morse.Contains(s)) return alphabet[morse.IndexOf(s)].ToString();
			return s.Chunk(3).Select(st => alphabet[morse.IndexOf(st)]).Aggregate("(", (a, b) => a + b) + ")";
		}).Aggregate("", (a, b) => a + b)+spaceConfig;
		ktPages = ktEncrypt.Chunk(9);
		print(ktPages.toString());
	}
	
	void solve()
	{
		GetComponent<KMAudio>().HandlePlayGameSoundAtTransform(KMSoundOverride.SoundEffect.CorrectChime, transform);
		GetComponent<KMBombModule>().HandlePass();
		_moduleSolved = true;
		dwText.text = "SOLVED!";
		ktText.text = "SOLVED!";

	}

	void backspace()
	{
		if (currentAnswer.Length == 0) return;
		currentAnswer = currentAnswer.Substring(0, currentAnswer.Length - 1);
		updateScreens();
	}

	void keypress(char c)
	{
		if (currentAnswer.Length == 6) return;
		currentAnswer += c;
		updateScreens();
	}

	void submit()
	{
		if (currentAnswer == generatedAnswer) solve();
		else GetComponent<KMBombModule>().HandleStrike();
	}
	
	void updateScreens()
	{
		ansText.text = currentAnswer;
		dwText.text = dwValues[dwPage];
		ktText.text = ktPages[ktPage];
	}
	
	// Update is called once per frame
	void Update ()
	{
		if (_moduleSolved || !_moduleSelected) return;
		if (Input.GetKeyDown(KeyCode.Backspace)) backspace();
		if (Input.GetKeyDown(KeyCode.Return)) submit();
		for (var ltr = 0; ltr < alphabet.Length; ltr++) 
			if (Input.GetKeyDown(alphabet[ltr].ToString().ToLower())) 
				keypress(alphabet[ltr]);
	}

	public IEnumerator ProcessTwitchCommand(string command)
	{
		yield return null;
		command = command.ToUpper();
		switch (command)
		{
			case "TL": buttons[0].OnInteract(); yield break;
			case "TR": buttons[1].OnInteract(); yield break;
			case "BL": buttons[2].OnInteract(); yield break;
			case "BR": buttons[3].OnInteract(); yield break;
			default:
			{
				if (command.Length == 6 && Regex.IsMatch(command, "[A-Z]+"))
				{
					currentAnswer = command;
					updateScreens();
					submit();
					yield break;
				}
				else
				{
					yield return "sendtochaterror Invalid command.";
					yield break;
				}
			}
		}
	}

	public IEnumerator TwitchHandleForcedSolve()
	{
		yield return null;
		currentAnswer = generatedAnswer;
		updateScreens();
		submit();
	}
}
